channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - python=3.10
  - xeus-lite
  - xeus-python
  - ipywidgets
  - matplotlib
  - numpy
  - pandas
  - scipy
  - sympy
  - pip
  - pip:
      - ..