name: Publish to TestPyPI

on:
  # Manual trigger
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: paros_dist
          path: "dist/"
        
  publish_to_testpypi:
    name: Publish to TestPyPI
    runs-on: ubuntu-latest
    environment: TestPyPI
    needs: build

    permissions:
      id-token: write

    steps:
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: paros_dist
          path: dist
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.8.11
        with:
          repository-url: https://test.pypi.org/legacy/
